<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container67bpaz6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container67bpaz6/appProdProjectContainer.php') {
    touch(__DIR__.'/Container67bpaz6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container67bpaz6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container67bpaz6\appProdProjectContainer([
    'container.build_hash' => '67bpaz6',
    'container.build_id' => 'defe406c',
    'container.build_time' => 1702573669,
], __DIR__.\DIRECTORY_SEPARATOR.'Container67bpaz6');
