<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYKE7qFQ\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYKE7qFQ/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerYKE7qFQ.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerYKE7qFQ\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerYKE7qFQ\appAppKernelProdContainer([
    'container.build_hash' => 'YKE7qFQ',
    'container.build_id' => 'f6e01c04',
    'container.build_time' => 1699694561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYKE7qFQ');
