<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQljjfq4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQljjfq4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQljjfq4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQljjfq4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQljjfq4\appProdProjectContainer([
    'container.build_hash' => 'Qljjfq4',
    'container.build_id' => 'a5317abd',
    'container.build_time' => 1701790791,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQljjfq4');
